// /* Automatically generated by './build/bin/build-init.js' */
// import 'plugin/assets/font/iconfont/iconfont.css';
// import 'plugin/assets/font/iconfont/iconfont.js';
// import Vue from 'vue';
// import App from './App.vue';
// import router from './route.config';
// import store from './store';
// import Element from 'element-ui';
// import 'element-ui/lib/theme-chalk/index.css';
// import i18n from './i18ns/index';
// import { hasPermission } from '../src/utils/permissionMapping/permissionMapping';
// import EdspTestUi, { edspTestUiStore, edspTestUiLang } from '../src/index';

// Vue.config.devtools = true;
// Vue.config.productionTip = false; // 生产环境关掉提示
// Vue.config.silent = true;
// Vue.use(Element, {
//   size: 'medium', // set element-ui default size
//   i18n: (key, value) => i18n.t(key, value)
// });

// Vue.use(EdspTestUi, {
//   i18n: (key, value) => i18n.t(key, value)
// });
// i18n.mergeLocaleMessage('zh', edspTestUiLang["zh-CN"]);
// i18n.mergeLocaleMessage('en', edspTestUiLang.en);
// store.registerModule('edspTestUiStore', edspTestUiStore);

// Vue.prototype.$hasPermission = hasPermission;
// const loadingEle = document.getElementById('_loading');
// loadingEle && (loadingEle.style.display = 'none');

// new Vue({
//   router,
//   store,
//   i18n,
//   render: (h) => h(App),
// }).$mount('#app');
import 'plugin/entry.js';
import "mone-uportal-plugin/main.js";