/* Automatically generated by './build/bin/build-init.js' */
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
// import 'plugin/assets/font/iconfont/iconfont.css';
// import 'plugin/assets/font/iconfont/iconfont.js';
import Vue from 'vue';
// @ts-ignore
import App from './App.vue';
import router from './route.config.js';
import Element from 'element-ui';
import 'element-ui/lib/theme-chalk/index.css';
import store from './store/index';
import i18n from './i18ns/index';
// 用于markdown展示
// @ts-ignore
import { hasPermission } from '../src/utils/permissionMapping/permissionMapping';
import demoBlock from './layout/components/demo-block.vue';
import hljs from 'highlight.js';
import EdspTestUi, { edspTestUiStore, edspTestUiLang } from '../src/index.js';

// VUE配置参数
Vue.config.devtools = true;
Vue.config.productionTip = false; // 生产环境关掉提示
Vue.config.silent = true;

// 插件使用
Vue.use(Element, {
  size: 'medium', // set element-ui default size
  i18n: (key, value) => i18n.t(key, value)
});

Vue.use(EdspTestUi, {
  i18n: (key, value) => i18n.t(key, value)
});
i18n.mergeLocaleMessage('zh', edspTestUiLang["zh-CN"]);
i18n.mergeLocaleMessage('en', edspTestUiLang.en);
store.registerModule('edspTestUiStore', edspTestUiStore);

// 组件
Vue.component('demo-block', demoBlock);
router.afterEach(route => {
  Vue.nextTick(() => {
    const blocks = document.querySelectorAll('pre code');
    Array.prototype.forEach.call(blocks, hljs.highlightBlock);
  });
});

Vue.prototype.$hasPermission = hasPermission;
const loadingEle = document.getElementById('_loading');
loadingEle && (loadingEle.style.display = 'none');

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  i18n,
  components: { App },
  template: '<App/>'
});
