/* Automatically generated by './build/bin/build-lang.js' */
import deepmerge from 'deepmerge';
const lang = {};
const ctx0 = require.context('./en', true, /.ts$/);
lang['en'] = ctx0.keys().reduce((total, key) => deepmerge(total, ctx0(key).default), {});
const ctx1 = require.context('./zh-CN', true, /.ts$/);
lang['zh-CN'] = ctx1.keys().reduce((total, key) => deepmerge(total, ctx1(key).default), {});
export default lang;
